Class {
	#name : #PlayerActionDescriptions,
	#superclass : #Object,
	#category : #'DM-Match-Request-Model'
}

{ #category : #accessing }
PlayerActionDescriptions class >> chargeMana [

	^ 'Charge mana'
]

{ #category : #accessing }
PlayerActionDescriptions class >> drawCard [

	^ 'Draw a card'
]

{ #category : #accessing }
PlayerActionDescriptions class >> summonCreature [

	^ 'Summon a creature'
]
